# Generated by Django 4.2.1 on 2023-09-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'chapter_table',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DashboardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dashboard_table',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_image', models.CharField(max_length=255)),
                ('student_email', models.CharField(max_length=255)),
                ('student_gender', models.CharField(max_length=100)),
                ('student_college_name', models.CharField(max_length=255)),
                ('student_dob', models.CharField(max_length=255)),
                ('standard', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'student_table',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'subject_table',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_tutorial', models.CharField(max_length=255)),
                ('video_caption', models.CharField(max_length=255)),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='HemanApp.chaptermodel')),
            ],
            options={
                'db_table': 'video_tutorial_table',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TextTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_file', models.CharField(max_length=255)),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text', to='HemanApp.chaptermodel')),
            ],
            options={
                'db_table': 'texttutorial_table',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='chaptermodel',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='HemanApp.subjectmodel'),
        ),
    ]
